
package radio;

/**
 * @author Rodrigo Urrutia 16139
 * @author Kevin Macario 17369
 * @version 19.01.2018
 * Se encarga de generar la interfaz del usuario para que el mismo pueda utilizar las funciones de la Radio. 
 */
public class RadioGUI extends javax.swing.JFrame {

    /**
     * Creates new form RadioGUI
     */
    private Radio r = new Radio();
    
    
    boolean validar = false;
    String estacion = r.mostrarEstacion();
    
    
    public RadioGUI() {
        initComponents();
        Off();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        estacion1Btt = new javax.swing.JButton();
        estacion2Btt = new javax.swing.JButton();
        estacion3Btt = new javax.swing.JButton();
        estacion4Btt = new javax.swing.JButton();
        estacion5Btt = new javax.swing.JButton();
        estacion6Btt = new javax.swing.JButton();
        estacion7Btt = new javax.swing.JButton();
        estacion8Btt = new javax.swing.JButton();
        estacion9Btt = new javax.swing.JButton();
        estacion10Btt = new javax.swing.JButton();
        estacion11Btt = new javax.swing.JButton();
        estacion12Btt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        apagarBtt = new javax.swing.JButton();
        atrasBtt = new javax.swing.JButton();
        adelanteBtt = new javax.swing.JButton();
        encenderBtt = new javax.swing.JButton();
        frecuenciaLbl = new javax.swing.JLabel();
        estacionLbl = new javax.swing.JLabel();
        cambiarBtt = new javax.swing.JButton();
        guardarBtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        estacion1Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion1Btt.setText("1");
        estacion1Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion1BttActionPerformed(evt);
            }
        });

        estacion2Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion2Btt.setText("2");
        estacion2Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion2BttActionPerformed(evt);
            }
        });

        estacion3Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion3Btt.setText("3");
        estacion3Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion3BttActionPerformed(evt);
            }
        });

        estacion4Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion4Btt.setText("4");
        estacion4Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion4BttActionPerformed(evt);
            }
        });

        estacion5Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion5Btt.setText("5");
        estacion5Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion5BttActionPerformed(evt);
            }
        });

        estacion6Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion6Btt.setText("6");
        estacion6Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion6BttActionPerformed(evt);
            }
        });

        estacion7Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion7Btt.setText("7");
        estacion7Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion7BttActionPerformed(evt);
            }
        });

        estacion8Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion8Btt.setText("8");
        estacion8Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion8BttActionPerformed(evt);
            }
        });

        estacion9Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion9Btt.setText("9");
        estacion9Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion9BttActionPerformed(evt);
            }
        });

        estacion10Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion10Btt.setText("10");
        estacion10Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion10BttActionPerformed(evt);
            }
        });

        estacion11Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion11Btt.setText("11");
        estacion11Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion11BttActionPerformed(evt);
            }
        });

        estacion12Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion12Btt.setText("12");
        estacion12Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion12BttActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Estaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estacion1Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion4Btt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion10Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion7Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(estacion5Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estacion2Btt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(estacion11Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estacion8Btt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estacion6Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion3Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion9Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion12Btt))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion1Btt)
                    .addComponent(estacion2Btt)
                    .addComponent(estacion3Btt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion4Btt)
                    .addComponent(estacion5Btt)
                    .addComponent(estacion6Btt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion7Btt)
                    .addComponent(estacion8Btt)
                    .addComponent(estacion9Btt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion10Btt)
                    .addComponent(estacion11Btt)
                    .addComponent(estacion12Btt))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("RADIO");

        apagarBtt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        apagarBtt.setText("Apagar");
        apagarBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarBttActionPerformed(evt);
            }
        });

        atrasBtt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        atrasBtt.setText("-");
        atrasBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBttActionPerformed(evt);
            }
        });

        adelanteBtt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        adelanteBtt.setText("+");
        adelanteBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelanteBttActionPerformed(evt);
            }
        });

        encenderBtt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        encenderBtt.setText("Encender");
        encenderBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encenderBttActionPerformed(evt);
            }
        });

        frecuenciaLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        frecuenciaLbl.setText("FM");

        estacionLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        estacionLbl.setText("87.9");

        cambiarBtt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cambiarBtt.setText("Cambiar frecuencia (FM/AM)");
        cambiarBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarBttActionPerformed(evt);
            }
        });

        guardarBtt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guardarBtt.setText("Guardar frecuencia");
        guardarBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encenderBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(apagarBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(adelanteBtt)
                                        .addGap(18, 18, 18)
                                        .addComponent(atrasBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(frecuenciaLbl)
                                        .addGap(36, 36, 36)
                                        .addComponent(estacionLbl)))
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(cambiarBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(guardarBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(encenderBtt)
                    .addComponent(apagarBtt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estacionLbl)
                            .addComponent(frecuenciaLbl))
                        .addGap(28, 28, 28)
                        .addComponent(cambiarBtt)
                        .addGap(18, 18, 18)
                        .addComponent(guardarBtt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adelanteBtt)
                            .addComponent(atrasBtt))
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void estacion3BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion3BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(3);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(3));  
            frecuenciaLbl.setText(r.obtenerEstado());
        }    
    }//GEN-LAST:event_estacion3BttActionPerformed

    private void estacion1BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion1BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(1);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(1));  
            frecuenciaLbl.setText(r.obtenerEstado());
        }     
    }//GEN-LAST:event_estacion1BttActionPerformed

    private void estacion2BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion2BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(2);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(2));  
            frecuenciaLbl.setText(r.obtenerEstado());
        } 
    }//GEN-LAST:event_estacion2BttActionPerformed

    private void estacion4BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion4BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(4);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(4));  
            frecuenciaLbl.setText(r.obtenerEstado());
        }  
    }//GEN-LAST:event_estacion4BttActionPerformed

    private void estacion5BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion5BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(5);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(5));  
            frecuenciaLbl.setText(r.obtenerEstado());
        } 
    }//GEN-LAST:event_estacion5BttActionPerformed

    private void estacion6BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion6BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(6);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(6));  
            frecuenciaLbl.setText(r.obtenerEstado());
        }  
    }//GEN-LAST:event_estacion6BttActionPerformed

    private void estacion7BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion7BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(7);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(7));  
            frecuenciaLbl.setText(r.obtenerEstado());
        } 
    }//GEN-LAST:event_estacion7BttActionPerformed

    private void estacion8BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion8BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(8);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(8));  
            frecuenciaLbl.setText(r.obtenerEstado());
        } 
    }//GEN-LAST:event_estacion8BttActionPerformed

    private void estacion9BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion9BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(9);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(9));  
            frecuenciaLbl.setText(r.obtenerEstado());
        }  
    }//GEN-LAST:event_estacion9BttActionPerformed

    private void estacion10BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion10BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(10);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(10));  
            frecuenciaLbl.setText(r.obtenerEstado());
        } 
    }//GEN-LAST:event_estacion10BttActionPerformed

    private void estacion11BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion11BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(11);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(11));  
            frecuenciaLbl.setText(r.obtenerEstado());
        } 
    }//GEN-LAST:event_estacion11BttActionPerformed

    private void estacion12BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion12BttActionPerformed
        if (validar == true){       
            r.guardarEstacionActual(12);
            validar = false;
        }    
        if (validar == false){         
            estacionLbl.setText(r.obtenerEstacion(12));  
            frecuenciaLbl.setText(r.obtenerEstado());
        }   
    }//GEN-LAST:event_estacion12BttActionPerformed

    private void encenderBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encenderBttActionPerformed
        r.prender();
        On();
    }//GEN-LAST:event_encenderBttActionPerformed

    private void apagarBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarBttActionPerformed
        r.apagar();
        Off();
    }//GEN-LAST:event_apagarBttActionPerformed

    private void adelanteBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelanteBttActionPerformed
        estacionLbl.setText(r.frecAdelante());
        estacion=r.mostrarEstacion();
    }//GEN-LAST:event_adelanteBttActionPerformed

    private void atrasBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBttActionPerformed
        estacionLbl.setText(r.frecAtras());   
        estacion=r.mostrarEstacion();
    }//GEN-LAST:event_atrasBttActionPerformed

    private void cambiarBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarBttActionPerformed
        r.cambioFrecuencia();
        frecuenciaLbl.setText(r.obtenerEstado());
        estacionLbl.setText(r.mostrarEstacion());        
    }//GEN-LAST:event_cambiarBttActionPerformed

    private void guardarBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBttActionPerformed
        validar = true;        
    }//GEN-LAST:event_guardarBttActionPerformed

    private void On(){
        estacionLbl.setVisible(true);
        frecuenciaLbl.setVisible(true);
        estacion1Btt.setVisible(true);
        estacion2Btt.setVisible(true);
        estacion3Btt.setVisible(true);
        estacion4Btt.setVisible(true);
        estacion5Btt.setVisible(true);
        estacion6Btt.setVisible(true);
        estacion7Btt.setVisible(true);
        estacion8Btt.setVisible(true);
        estacion9Btt.setVisible(true);
        estacion10Btt.setVisible(true);
        estacion11Btt.setVisible(true);
        estacion12Btt.setVisible(true);
        adelanteBtt.setVisible(true);
        atrasBtt.setVisible(true);
        cambiarBtt.setVisible(true);
        guardarBtt.setVisible(true);
        jPanel1.setVisible(true);
    }
    
    private void Off(){
        estacionLbl.setVisible(false);
        frecuenciaLbl.setVisible(false);
        estacion1Btt.setVisible(false);
        estacion2Btt.setVisible(false);
        estacion3Btt.setVisible(false);
        estacion4Btt.setVisible(false);
        estacion5Btt.setVisible(false);
        estacion6Btt.setVisible(false);
        estacion7Btt.setVisible(false);
        estacion8Btt.setVisible(false);
        estacion9Btt.setVisible(false);
        estacion10Btt.setVisible(false);
        estacion11Btt.setVisible(false);
        estacion12Btt.setVisible(false);
        adelanteBtt.setVisible(false);
        atrasBtt.setVisible(false);
        cambiarBtt.setVisible(false);
        guardarBtt.setVisible(false);
        jPanel1.setVisible(false);
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adelanteBtt;
    private javax.swing.JButton apagarBtt;
    private javax.swing.JButton atrasBtt;
    private javax.swing.JButton cambiarBtt;
    private javax.swing.JButton encenderBtt;
    private javax.swing.JButton estacion10Btt;
    private javax.swing.JButton estacion11Btt;
    private javax.swing.JButton estacion12Btt;
    private javax.swing.JButton estacion1Btt;
    private javax.swing.JButton estacion2Btt;
    private javax.swing.JButton estacion3Btt;
    private javax.swing.JButton estacion4Btt;
    private javax.swing.JButton estacion5Btt;
    private javax.swing.JButton estacion6Btt;
    private javax.swing.JButton estacion7Btt;
    private javax.swing.JButton estacion8Btt;
    private javax.swing.JButton estacion9Btt;
    private javax.swing.JLabel estacionLbl;
    private javax.swing.JLabel frecuenciaLbl;
    private javax.swing.JButton guardarBtt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
