
package radio;

/**
 * @author Rodrigo Urrutia 16139
 * @author Kevin Macario 17369
 * @version 19.01.2018
 * Se encarga de generar la interfaz del usuario para que el mismo pueda utilizar las funciones de la Radio. 
 */
public class RadioGUI extends javax.swing.JFrame {

    /**
     * Creates new form RadioGUI
     */
    private Radio r = new Radio();
    
    public RadioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        estacion1Btt = new javax.swing.JButton();
        estacion2Btt = new javax.swing.JButton();
        estacion3Btt = new javax.swing.JButton();
        estacion4Btt = new javax.swing.JButton();
        estacion5Btt = new javax.swing.JButton();
        estacion6Btt = new javax.swing.JButton();
        estacion7Btt = new javax.swing.JButton();
        estacion8Btt = new javax.swing.JButton();
        estacion9Btt = new javax.swing.JButton();
        estacion10Btt = new javax.swing.JButton();
        estacion11Btt = new javax.swing.JButton();
        estacion12Btt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ApagarButton = new javax.swing.JButton();
        BajarButton = new javax.swing.JButton();
        SubirButton = new javax.swing.JButton();
        EncenderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        estacion1Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion1Btt.setText("1");
        estacion1Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion1BttActionPerformed(evt);
            }
        });

        estacion2Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion2Btt.setText("2");
        estacion2Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion2BttActionPerformed(evt);
            }
        });

        estacion3Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion3Btt.setText("3");
        estacion3Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion3BttActionPerformed(evt);
            }
        });

        estacion4Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion4Btt.setText("4");
        estacion4Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion4BttActionPerformed(evt);
            }
        });

        estacion5Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion5Btt.setText("5");
        estacion5Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion5BttActionPerformed(evt);
            }
        });

        estacion6Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion6Btt.setText("6");
        estacion6Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion6BttActionPerformed(evt);
            }
        });

        estacion7Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion7Btt.setText("7");
        estacion7Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion7BttActionPerformed(evt);
            }
        });

        estacion8Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion8Btt.setText("8");
        estacion8Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion8BttActionPerformed(evt);
            }
        });

        estacion9Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion9Btt.setText("9");
        estacion9Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion9BttActionPerformed(evt);
            }
        });

        estacion10Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion10Btt.setText("10");
        estacion10Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion10BttActionPerformed(evt);
            }
        });

        estacion11Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion11Btt.setText("11");
        estacion11Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion11BttActionPerformed(evt);
            }
        });

        estacion12Btt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        estacion12Btt.setText("12");
        estacion12Btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacion12BttActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Estaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estacion1Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion4Btt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion10Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion7Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(estacion5Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estacion2Btt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(estacion11Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estacion8Btt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estacion6Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion3Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion9Btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estacion12Btt))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion1Btt)
                    .addComponent(estacion2Btt)
                    .addComponent(estacion3Btt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion4Btt)
                    .addComponent(estacion5Btt)
                    .addComponent(estacion6Btt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion7Btt)
                    .addComponent(estacion8Btt)
                    .addComponent(estacion9Btt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estacion10Btt)
                    .addComponent(estacion11Btt)
                    .addComponent(estacion12Btt))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("RADIO");

        ApagarButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ApagarButton.setText("Apagar");
        ApagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarButtonActionPerformed(evt);
            }
        });

        BajarButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BajarButton.setText("Reducir Frecuencia");
        BajarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajarButtonActionPerformed(evt);
            }
        });

        SubirButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SubirButton.setText("Subir Frecuencia");
        SubirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirButtonActionPerformed(evt);
            }
        });

        EncenderButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EncenderButton.setText("Encender");
        EncenderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncenderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BajarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ApagarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EncenderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EncenderButton)
                        .addGap(5, 5, 5)
                        .addComponent(ApagarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BajarButton)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void estacion3BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion3BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion3BttActionPerformed

    private void estacion1BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion1BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion1BttActionPerformed

    private void estacion2BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion2BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion2BttActionPerformed

    private void estacion4BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion4BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion4BttActionPerformed

    private void estacion5BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion5BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion5BttActionPerformed

    private void estacion6BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion6BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion6BttActionPerformed

    private void estacion7BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion7BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion7BttActionPerformed

    private void estacion8BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion8BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion8BttActionPerformed

    private void estacion9BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion9BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion9BttActionPerformed

    private void estacion10BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion10BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion10BttActionPerformed

    private void estacion11BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion11BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion11BttActionPerformed

    private void estacion12BttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacion12BttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estacion12BttActionPerformed

    private void EncenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncenderButtonActionPerformed
        r.prender();
    }//GEN-LAST:event_EncenderButtonActionPerformed

    private void ApagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApagarButtonActionPerformed

    private void SubirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubirButtonActionPerformed

    private void BajarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BajarButtonActionPerformed

    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApagarButton;
    private javax.swing.JButton BajarButton;
    private javax.swing.JButton EncenderButton;
    private javax.swing.JButton SubirButton;
    private javax.swing.JButton estacion10Btt;
    private javax.swing.JButton estacion11Btt;
    private javax.swing.JButton estacion12Btt;
    private javax.swing.JButton estacion1Btt;
    private javax.swing.JButton estacion2Btt;
    private javax.swing.JButton estacion3Btt;
    private javax.swing.JButton estacion4Btt;
    private javax.swing.JButton estacion5Btt;
    private javax.swing.JButton estacion6Btt;
    private javax.swing.JButton estacion7Btt;
    private javax.swing.JButton estacion8Btt;
    private javax.swing.JButton estacion9Btt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
